- examples/index.ts
- src/core/renderers/CoreShader.ts
- src/core/renderers/webgl/WebGlCoreRenderOp.ts
- src/core/renderers/webgl/WebGlCoreRenderer.ts
- src/core/renderers/webgl/WebGlCoreShader.ts
- src/core/renderers/webgl/shaders/DynamicShader.ts
- src/core/renderers/webgl/shaders/RoundedRectangle.ts
- src/core/renderers/webgl/shaders/SdfShader.ts
- src/utils.ts
The `u_dimensions` uniform used by both RoundedRectangleShader and DynamicShader are automatically filled in per quad that is rendered. The way it was done originally makes it difficult for the renderer to tell generally if two consecutive quads that use the same shaders can be batched into the same render operation.
With `$` prefixed automatic shader props, Shaders opt-into using them and simply set their defaults to a compatible type (for `$dimensions` it is simply a Rect). The renderer, during addQuad() will fill our the correct values for automatic shader props prior to rendering.
Shaders now can implement a `canBatchShaderProps()` method to compare two sets of shader props to see if it can be batched into the same render opertion. The default behavior is to return false. Some Shaders …
> Implement automatic `$` prefixed shader props

- src/main-api/RendererMain.ts
Expose the `settings` object from the RendererMain instance for easy access
> RendererMain: Expose renderer settings

- package.json
I've tested this locally and it fixes the issue where sourcemaps aren't found cause they are looking for the originally TS files which aren't in the dist directory
> include src files for sourcemaps

- package-lock.json
- package.json
- Fixes a Vite error that users of the Renderer experienced due to missing source maps
> Update ThreadX to v0.3.3

- package.json
- Fixes all remaining Vite sourcemap errors that users of the Renderer experienced
> Include `exports` files for SourceMaps

- examples/common/Character.ts
- examples/common/ExampleSettings.ts
- examples/index.ts
- examples/tests/alpha-blending.ts
- examples/tests/animation.ts
- examples/tests/clipping.ts
- examples/tests/dynamic-shader.ts
- examples/tests/mount-pivot.ts
- examples/tests/robot.ts
- examples/tests/rotation.ts
- examples/tests/scale.ts
- examples/tests/test.ts
- examples/tests/text-events.ts
- examples/tests/text.ts
- examples/tests/texture-memory-stress.ts
- examples/tests/textures.ts
- examples/tests/zIndex.ts
- src/core/CoreTextureManager.ts
- src/core/renderers/webgl/shaders/DynamicShader.ts
- src/core/textures/SubTexture.ts
- src/main-api/INode.ts
- src/main-api/RendererMain.ts
- src/main-api/texture-usage-trackers/FinalizationRegistryTextureUsageTracker.ts
- src/main-api/texture-usage-trackers/ManualCountTextureUsageTracker.ts
- src/main-api/texture-usage-trackers/TextureUsageTracker.ts
- src/render-drivers/main/MainOnlyNode.ts
- src/render-drivers/threadx/ThreadXMainNode.ts
- src/render-drivers/threadx/worker/ThreadXRendererNode.ts
- Usaged-Based Texture Memory management now defaults to a new manual reference count and time threshold strategy.
- This removes the requirement of the FinalizationRegistry browser feature which is not available prior to chrome 84 / WPE 2.38. 
- The prior behavior is still available by setting a new experimental renderer setting to `true`:
- `experimental_FinalizationRegistryTextureUsageTracker`
- Added `texture-memory-stress` test with instructions on how to perform.
- Example tests may now export a `customSettings` function which returns any renderer settings overrides that the test requires to run. These settings are applied on top of all of the defaults specified by the example test launcher.
- Improve type checking for EffectDesc
- `type` now determines the specific properties types …
> Replace FinalizationRegistry based Texture Usage GC with Manual Strategy

- src/core/text-rendering/renderers/CanvasTextRenderer.ts
- src/core/text-rendering/renderers/LightningTextTextureRenderer.ts
- This allows the Renderer to run on devices that do not support OffscreenCanvas which is not available in prior to Chrome 69 / WPE 2.38
> Use HTMLCanvasElement instead of OffscreenCanvas if it isn't available.

- src/core/text-rendering/renderers/CanvasTextRenderer.ts
This PR aims to solve [this issue](https://github.com/lightning-js/renderer/issues/26#issuecomment-1750438486).
Solution: If the `OffscreenCanvas` is available but it's `context` is not, the code falls back to using `HTMLCanvasElement` and it's context.
> FIX: Offscreen Canvas context is not available

- README.md
- examples/package.json
- examples/vite.config.ts
- package.json
- src/core/renderers/webgl/WebGlCoreCtxSubTexture.ts
- src/core/renderers/webgl/WebGlCoreCtxTexture.ts
- src/core/renderers/webgl/WebGlCoreShader.ts
- src/core/renderers/webgl/shaders/RoundedRectangle.ts
- src/core/textures/ColorTexture.ts
- src/core/textures/ImageTexture.ts
- src/core/textures/NoiseTexture.ts
- src/core/textures/SubTexture.ts
- src/core/textures/Texture.ts
- Fixes remaining issues when trying to run the Renderer on WPE 2.28 browser and possibly lower.
- Tested on a production XG2v2 device.
- For an application using the Renderer to work on this browser, its build target MUST be set to ES2019 or lower. 
- To run the Renderer Example Tests on legacy browsers, you must build/run the production version of the tests.
- Fixes
- #43
- #44
- #45
- Added `npm run prod` command to run the Example Tests in production mode (required to run the tests on legacy browsers)
> Fix WPE 2.28 support

- examples/tests/dynamic-shader.ts
- exports/core-api.ts
- src/core/CoreShaderManager.ts
- src/core/renderers/webgl/shaders/DynamicShader.ts
- src/core/renderers/webgl/shaders/effects/FadeOutEffect.ts
- src/core/renderers/webgl/shaders/effects/LinearGradientEffect.ts
- src/core/renderers/webgl/shaders/effects/RadiusEffect.ts
- Refactored the Effects to the ShaderManager, this way a developer can add their own custom effects.
- Added more docs on the FadeOutEffect and RadiusEffect.
- *breaking* Angle property is now in Radians not in Degrees. The reason for this change is that we only use radians in the core, and it saves a calculation for each pixel from degrees to radians. The dynamic-shader example has a example function that calculates degrees to radians (PI / 180 * degrees)
> Refactor Effects + changes

- exports/main-api.ts
- src/core/animations/CoreAnimation.ts
- src/main-api/INode.ts
- src/render-drivers/main/MainOnlyNode.ts
- src/render-drivers/threadx/ThreadXMainNode.ts
- src/render-drivers/threadx/worker/ThreadXRendererNode.ts
- Internally rename IAnimationSettings to AnimationSettings
> Expose AnimationSettings interface from Main API

- README.md
- RELEASE.md
Added the manual release procedure that I've been employing for releases. It does require pushing to the `main` branch because it relies on the standard `npm version` command in order to create the commit and tag for the version. I'd prefer a more automated approach in the future. Let me know if anyone has any feedback.
> Add release procedure

- examples/common/Component.ts
- examples/common/ExampleSettings.ts
- examples/common/LocalStorage.ts
- examples/common/LoremIpsum.ts
- examples/common/PageContainer.ts
- examples/common/paginateTestRows.ts
- exports/utils.ts
- src/core/text-rendering/renderers/SdfTextRenderer/SdfTextRenderer.ts
- src/utils.ts
New exported util function to make it easier to folks to convert degrees to radians. Framework libraries may re-export this if they'd like.
```
import { deg2Rad } from "@lightningjs/renderer/utils";
```
> Add deg2rad exported util

- examples/common/utils.ts
- examples/tests/animation.ts
- examples/tests/clipping.ts
- src/core/Stage.ts
The clipping area is now scaled appropriately according to the `scale` properties.
Clipping is also now disabled when a clipping node is rotated (Lightning 2 behavior).
Fixes #54
> Fix clipping when node is scaled

- examples/common/utils.ts
- examples/tests/alpha-blending.ts
- examples/tests/text-events.ts
- examples/tests/textures.ts
- src/common/CommonTypes.ts
- src/core/CoreNode.ts
- src/core/CoreTextNode.ts
- src/core/text-rendering/renderers/TextRenderer.ts
- src/core/textures/SubTexture.ts
- src/core/textures/Texture.ts
- src/render-drivers/main/MainOnlyNode.ts
- src/render-drivers/main/MainOnlyTextNode.ts
- src/render-drivers/threadx/worker/ThreadXRendererNode.ts
- src/render-drivers/threadx/worker/ThreadXRendererTextNode.ts
There were some issues that got merged in from #72 that caused some examples to break. I've fixed the issues and also refactored these types a bit more to reduce some ambiguity that had been present even before #72.
> Fix up issues with Text / Texture loaded/failed event refactor

- examples/tests/ds-effect-radial-progress.ts
- src/core/CoreShaderManager.ts
- src/core/renderers/webgl/shaders/DynamicShader.ts
- src/core/renderers/webgl/shaders/effects/RadialProgressEffect.ts
Radial Progress bar effect.
This is a masking type effect similar to Radius / border / fadeout.
> Radial Progress Dynamic Shader Effect

- examples/tests/test.ts
setInteral(0) on Safari causes browser to call that function as fast as possible
> Example Page: increase interval above 0

- src/render-drivers/main/MainCoreDriver.ts
Both the root node and the first node get id: 1, although it doesn't matter with a nested Tree. It is an issue when experimenting with different tree strategies that rely on unique node id's.
> Fixes duplicate node id.

- .github/workflows/tests.yml
- visual-regression/README.md
Sometimes visual regression test fail on GitHub actions but pass locally even in `--ci` mode!
See included README update. The `failed-results` directory is now uploaded as an artifact of at the GitHub Actions workflow so that they can be examined.
> Upload failed Visual Regression tests

- .github/workflows/tests.yml
By default, when our PR check runs against each PR it is only testing the specific commit HEAD of the PR branch, without necessarily also considering the current HEAD of `main`, unless that commit has been merged in manually into the PR branch. Merge queues provide a way of automating this.
https://docs.github.com/en/repositories/configuring-branches-and-merges-in-your-repository/configuring-pull-request-merges/managing-a-merge-queue
> GitHub Actions: Turn on merge queue

- examples/README.md
- examples/index.ts
When `fps` is set on a run of an Example Test, skipping the first 10 fps samples, every 30 fps samples print out a statistics summary of those samples.
Example:
```
---------------------------------
Average FPS: 27.25
Median FPS: 26
P01 FPS: 19
P05 FPS: 26
P25 FPS: 26
Std Dev FPS: 2.7798381247835278
Num samples: 100
---------------------------------
```
> Examples: Implemented a statistics summary when `fps` is set

- src/core/CoreNode.ts
- src/core/CoreTextNode.ts
- src/core/Stage.ts
Add color: 0 to the node and don't provide any texture/image properties and it will be skipped in the render step.
> Perf: Skip nodes that have no renderable props.

- examples/README.md
- examples/common/StatTracker.ts
- examples/index.ts
- src/common/CommonTypes.ts
- src/core/Stage.ts
- src/core/lib/ContextSpy.ts
- src/core/renderers/webgl/WebGlCoreRenderer.ts
- src/main-api/ICoreDriver.ts
- src/main-api/RendererMain.ts
- src/render-drivers/main/MainCoreDriver.ts
- src/render-drivers/threadx/ThreadXCoreDriver.ts
- src/render-drivers/threadx/ThreadXRendererMessage.ts
- src/render-drivers/threadx/worker/renderer.ts
- src/utils.ts
When enabled by the `enableContextSpy` renderer option, the canvas context object (WebGL in the current case) will be instrumented with a spy mechanism that counts the number of calls to each context function. The number of calls to each function during the previous FPS interval will be included in the new `contextSpyData` key of the 'fpsUpdate' event.
The Context Spy can be enabled in Example Tests by the `contextSpy` boolean URL param. When enabled, a statistical calculation of each context function call will be reported after every FPS statistics summary. Because of this, the option requires that the `fps` URL param is also set to true, otherwise only a degradation of performance will occur without any output of the Context Spy data.
Example output:
``` …
```
> Context Spy

- examples/tests/stress-multi-level.ts
- examples/tests/stress-multi-texture.ts
- examples/tests/stress-single-level.ts
- `stress-single-level` (renamed from `stress`)
- Animates `100 * multiplier` image nodes with the same texture
- This tests one of the fastest render passes where everything is rendered with a single renderOp and texture bind.
- `stress-multi-level`
- Animates `100 * multiplier` container nodes each that have a child node with the same texture
- This tests the case where container nodes wrap an image node, which can result in a renderOp for each node draw and alternating texture binds, if not properly optimized.
- `stress-multi-texture`
- Animates `100 * multiplier` image nodes with two alternating textures
- This tests a worst case scenario where a new renderOp and texture bind is needed for each draw call.
> Implement distinct stress tests

- src/core/CoreNode.ts
Except when there is a texture set, this does not require an upfront width/height.
> Perf: Skip rendering of nodes that do not have a width/height property.

- src/core/renderers/webgl/shaders/effects/GrayscaleEffect.ts
The old Grayscale shader, had an `amount` prop which was missing in this version of the grayscale effect. This PR fixes the grayscale to fall in-line with what was expected of the grayscale shader in Lightning 2
> Update grayscale effect to fall in-line with L2 shader version

- src/core/lib/WebGlContextWrapper.ts
- src/core/renderers/webgl/WebGlCoreCtxSubTexture.ts
- src/core/renderers/webgl/WebGlCoreCtxTexture.ts
- src/core/renderers/webgl/WebGlCoreRenderOp.ts
- src/core/renderers/webgl/WebGlCoreRenderer.ts
- src/core/renderers/webgl/WebGlCoreShader.ts
- src/core/renderers/webgl/internal/RendererUtils.ts
- src/core/renderers/webgl/internal/ShaderUtils.ts
- src/core/renderers/webgl/shaders/DefaultShader.ts
- src/core/renderers/webgl/shaders/DefaultShaderBatched.ts
- src/core/renderers/webgl/shaders/DynamicShader.ts
- src/core/renderers/webgl/shaders/RoundedRectangle.ts
- src/core/renderers/webgl/shaders/SdfShader.ts
- src/core/text-rendering/renderers/SdfTextRenderer/SdfTextRenderer.ts
**Depends on #110**
- **DO NOT MERGE** until that PR is merged to main, and be sure to set the base to `main` after that happens.
This performance enhancement encapsulates the native WebGL context into a wrapper which keeps track of the state of some some heavy/frequent WebGL operations and filters out unnecessary calls to the native context.
See description above the WebGlContextWrapper class for more information on it.
The test on Chrome Desktop on my 2019 MacBook Pro showed a significant improvement in FPS for 6000 nodes when running the `stress-multi-texture` test. Total WebGL calls per frame were reduced by 78% and the median FPS was improved by 98%.
```
stress-multi-texture (chrome)
http://localhost:5173/?test=stress-multi-texture&overlay=false&fps=true&multiplier=60&contextSpy=true …
```
> Perf: Optimized WebGL Context Wrapper

- examples/tests/text-overflow-suffix.ts
- examples/tests/text-vertical-align.ts
- src/core/lib/WebGlContextWrapper.ts
The new WebGlContextWrapper was improperly assuming equality with deeply nested arrays so the transform uniform never gets updated.
Fixes #126
> Fix SDF text not moving with parent

- package.json
- pnpm-lock.yaml
- src/core/CoreNode.ts
- src/core/renderers/webgl/shaders/DynamicShader.ts
- src/core/utils.ts
Added Memize library to add a layer of caching for timing functions and Dynamic shader.
Optimized shader to return same default object which allows memize to use the object as a key efficiently. Thus most effects reuse the same props results.
> memize shaders and timing functions

- examples/tests/stress-multi-level-clipping.ts
- src/core/CoreNode.ts
- src/core/CoreTextNode.ts
- src/core/Stage.ts
- src/core/lib/utils.ts
- src/core/renderers/CoreRenderer.ts
- src/core/renderers/webgl/WebGlCoreRenderOp.ts
- src/core/renderers/webgl/WebGlCoreRenderer.ts
- src/core/text-rendering/renderers/CanvasTextRenderer.ts
- src/core/text-rendering/renderers/SdfTextRenderer/SdfTextRenderer.ts
- src/core/text-rendering/renderers/TextRenderer.ts
The goal is to reduce the number of object allocations and hence garbage collection memory pressure on objects that may be rapidly replaced during animations. In this case, the clipping rect was being newly allocated each time it was changed. This change makes it so there is only one clipping rect per Node that is persistently kept throughout the lifetime of the Node. The SDF text renderer also keeps a persistent clipping rect for its purposes.
This does not seem to have an impact on raw FPS performance:
```
Before Change:
---------------------------------
Average FPS: 25.16
Median FPS: 25
P01 FPS: 14
P05 FPS: 23
P25 FPS: 25
Std Dev FPS: 2.0135540717845153
Num samples: 100
---------------------------------
---------------------------------
Average FPS: 25.7
Median FPS: 26
P01 FPS: 14
P05 …
```
> Instantiate a single clipping Rect for each Node / Text Renderer State

- src/core/renderers/webgl/WebGlCoreRenderer.ts
Simple scenes that do not involve textures, text or any later mutations were not rendering to the canvas. This is due to the default texture "ColorTexture" not being loaded prior to the scene being rendered. This texture must be loaded before any solid color Nodes will render. When this issue was happening the RAF was paused right before the texture was loaded and that texture loaded event did not trigger a requestRender() from the stage.
The solution here is to request a render once from the stage after the default texture has loaded.
Fixes #123
> Fix simple scene rendering

- examples/tests/stress-single-level-text.ts
- src/core/lib/utils.ts
- src/core/text-rendering/renderers/SdfTextRenderer/SdfTextRenderer.ts
- src/core/text-rendering/renderers/SdfTextRenderer/internal/setRenderWindow.ts
This optimization is now more optimistic about laying out text that has the potential to be on screen. With this the x/y property setters are now more optimized to not schedule an update unless the text was not renderer previously and has the potential to be rendered now.
Replaces #130
> Perf: Optimize the setting of x/y props for SDF text

- examples/common/PageContainer.ts
Makes it easier to visually compare two non-sequential pages
> Add ability to navigate pages by number key for PageContainer test examples

- .eslintignore
- package-lock.json
- package.json
- scripts/please-use-pnpm.js
The Lightning renderer project uses PNPM as a package manager. And for anyone working on the renderer, using PNPM should obviously be required.
But for projects built on top of the renderer, there is no real reason to enforce the usage of PNPM.
Currently when installing the renderer as a dependency in an NPM based project, a warning is shown about unsupported engines. Which is not necesary and can cause confusion.
This change removes this warning from NPM installs using the renderer as dependency, while still enforcing PNPM when working directly on the renderer code itself.
> Remove PNPM warning for projects using the renderer as a dependency

- examples/index.ts
- src/main-api/Inspector.ts
- src/main-api/RendererMain.ts
Conditional inspector that can be enabled with:
```
enableInspector: true
```
Will replicate the Lightning node tree in a DIV DOM tree, and remap Lightning 3 node properties to applicable CSS properties for easy inspection using the web inspector in your devtools.
Note: currently does not support attaching stuff like `testId` as requested in the original issue #94. This requires an extension to the `INode` interface that will need some more consideration.
Notes:
* Inspector works off of `RendererMain` so it can support both ThreadX and single threaded mode.
* Inspector wraps arround `createNode`, `createTextNode` APIs using Proxies.
* Inspector has a rudimentary understanding of animations, to reflect the DOM tree with animations being executed. However this does not work with loops and …
> Inspector: Lightning 3 node tree in the DOM for debugging

- examples/tests/inspector.ts
- src/main-api/INode.ts
- src/main-api/Inspector.ts
- src/main-api/RendererMain.ts
- src/render-drivers/main/MainOnlyNode.ts
- src/render-drivers/threadx/ThreadXMainNode.ts
- src/render-drivers/utils.ts
This allows the consumer of the Node's or TextNode's to inject small data properties that will be returned and/or added in the inspector `node-*` attributes.
For example:
```
const dataNode = renderer.createNode({
width: 505,
height: 101,
x: 200,
y: 200,
src: logo,
parent: bg,
data: {
id :'dataNode',
number: 1,
boolean: true
}
});
```
In this case data: {} is an santized Map of key/values that will be stored on the main node.
*Note*: Custom data will not be passed to the CoreNode or ThreadX node. Thus data remains on the main thread and does not get forwarded to the Render thread in case of the ThreadX driver. This to avoid clashes/overhead on the ThreadX interface.
For performance reasons only strings, booleans and numbers are allowed. Passing in a nested object will not be permitted to …
> Feat: Allow custom data key/value storage on Nodes.

- src/core/text-rendering/TrFontManager.ts
- src/core/text-rendering/renderers/SdfTextRenderer/SdfTextRenderer.ts
Update the font resolver to return a font for different fontWeights. If a fontWeight is not available it will get a font based on the CSS rules: https://www.w3.org/TR/2018/REC-css-fonts-3-20180920/#font-matching-algorithm
Also memize the function for performance
> feat: add font weight fallbacks

- README.md
Aiming to provide solid clarity on what Lightning 3's goal of browser support is.
Added the Chrome v38 requirement after discussing with @wouterlucas. If we know for sure any other browser versions (and dates) let's discuss here so we can add them.
> README: Add browser targets section

- src/core/CoreTextureManager.ts
- src/core/lib/ImageWorker.ts
- src/core/renderers/webgl/WebGlCoreCtxTexture.ts
- src/core/renderers/webgl/internal/RendererUtils.ts
- src/core/textures/ImageTexture.ts
- src/core/textures/Texture.ts
In case the browser does not support createImageBitmap the renderer will fallback to using the Image() constructor using HTMLImageElement to fetch images.
**Note** This is slower over using createImageBitmap, Lightning will throw a console.warn to warn its users. 
Addresses: https://github.com/lightning-js/renderer/issues/192 and follows the same fallback pattern as Lightning 2.
This feature will allow the renderer to work on Chrome < 50 where createImageBitmap is not supported. See https://caniuse.com/createimagebitmap for more information.
> ImageTexture: Fall back to HTMLImageElement in case createImageBitmap is not available

- src/render-drivers/main/MainOnlyNode.ts
Setting parent was modifying the array so wasn't actually going through all the children... This actually works.
> fix: memory leak not deleting all children

- src/core/Stage.ts
- src/core/platform.ts
Currently we do not fire FPS update events when the renderloop is in RAF idle state. This can give the perception that the app is stuck on the previously rendered frame speed.
This changes the FPS events to fire on RAF idle loops as well.
> FPS: Update FPS when in idle RAF

- src/core/platform.ts
- src/main-api/ICoreDriver.ts
- src/main-api/RendererMain.ts
- src/render-drivers/main/MainCoreDriver.ts
Emit an idle event when renderer isnt performing any actions. Useful for frameworks to do work when nothing is happening. Also threadx doesnt need this as its a separate thread.
> feat: #196 add idle event

- src/core/CoreNode.ts
According to the dependency graph for CoreNodes, and the logic as I see it in the code, an update to a parent's premultiplied colors should not need to propagate/cascade down to its children.
> Perf: Remove unnecessary cascading of premultiply colors update

- src/main-api/Inspector.ts
- src/main-api/RendererMain.ts
- src/utils.ts
I was running into problems with import.meta.env not being defined in environments. This function should resolve my problems when running using CDNs that can't set these values since import.meta is protected during runtime.
> check production environment via function

- src/core/renderers/webgl/shaders/effects/LinearGradientEffect.ts
- src/core/renderers/webgl/shaders/effects/RadialGradientEffect.ts
Optimized gradient shaders for #159,
Moved color stops calculations to resolveDefaults function, since the calculation only needs to be done once in order to generate the shader source.
And removed the for loop in the fragment source.
> Optimized gradient shaders

- src/core/CoreNode.ts
Event emitted for "out of viewport" was spelled with a capital `P` in `viewport`.
For consistency (and to match the provided example) this should probably have been a lowercase `p`.
> Fixed casing of out of viewport event.

- src/core/text-rendering/renderers/SdfTextRenderer/internal/layoutText.ts
Another hack to prevent an infinite loop situation that was introduced in v0.8.0.
I've written up an issue to address more wholistically the issues with the SDF layout engine
- #223 
Fixes #220
> SDF: Fix infinite layout loop

- src/main-api/Inspector.ts
> fix: inspector adds div to text nodes as well

- src/core/renderers/webgl/shaders/DynamicShader.ts
Got the batch check for the dynamic shader working properly reducing the draw calls:
Draws without batch check:
Draws with batch check:
> added canBatchShaderProps to dynamic shader

- src/core/CoreNode.ts
This fix resolves skipping the InBounds state when the renderMargin is not configured. In most cases it means that the size of the bounds check is the same as the size of the viewport. With this fix it will still fire an inBounds event when going directly from outOfBounds to inViewport and vice versa.
> resolve isseus skipping inBounds state

- src/core/lib/ImageWorker.ts
Doesnt need to be there - another breaking thing in older Chrome
> remove another async

- src/main-api/Inspector.ts
- src/render-drivers/utils.ts
Fixes issue in #236 comments: unable to remove an attribute.
When using `data` prop:
1. Once a value is set, it can't be removed; it can only be replaced by another value,
2. Passing an `undefined` value results in `"undefined"` being serialized as the dataset value.
I thing there is an opportunity to use an `undefined` value to clear a property.
Note: I wasn't able to run visual regression tests and had issues with pre-commit hooks.
> Clear data attribute when value is undefined

- src/core/textures/ImageTexture.ts
Gets images loading in older browsers when cross domain. This is the same as what L2 did. Tested with TMDB app and its working.
> fix: cross image support on base images

- examples/common/AppCoreExtension.ts
- examples/index.ts
- src/core/CoreShaderManager.ts
- src/core/Stage.ts
- src/core/renderers/CoreRenderer.ts
- src/core/renderers/canvas/CanvasCoreRenderer.ts
- src/core/renderers/canvas/CanvasCoreTexture.ts
- src/core/renderers/canvas/internal/C2DShaderUtils.ts
- src/core/renderers/canvas/internal/ColorUtils.ts
- src/core/renderers/canvas/shaders/UnsupportedShader.ts
- src/core/renderers/webgl/WebGlCoreRenderer.ts
- src/core/text-rendering/renderers/SdfTextRenderer/SdfTextRenderer.ts
- src/main-api/RendererMain.ts
- src/render-drivers/main/MainCoreDriver.ts
- src/render-drivers/threadx/worker/renderer.ts
- src/utils.ts
Initial canvas 2D renderer.
Added `renderMode: 'webgl' | 'canvas'` renderer option.
https://github.com/lightning-js/renderer/assets/297963/5aaac948-7ae7-4c1c-a255-6de0a68359b8
Limitation:
- Only horizontal & vertical color gradients,
- Only `RoundedRectangle` "shader".
Future potential PRs:
- Canvas-text textures optimization to avoid doing Canvas -> ImageData -> Canvas
- Maybe a c2d shader API
Unsupported:
- All shaders (gracefully ignored) excepted `RoundedRectangle`,
- SDF text (fallback to canvas text).
Aside from that, all the examples render correctly! Rotation, clipping, tinting, spritesheets...
> Canvas 2D renderer

- examples/tests/viewport-events.ts
- src/core/CoreNode.ts
- src/render-drivers/main/MainOnlyNode.ts
A node in the visible area gets a inViewport event A node in bounds gets a inBounds event
A node outside viewport & bounds gets a outOfViewport event
Nodes that are init or outofview port will get a renderable false. All events have a previous state and new state accordingly.
**BREAKING CHANGE**
> Simplify viewport events

- src/core/utils.ts
This PR properly optimizes the getTimingFunction, which is called during animations, and drops the memize dependency. Applying memoization negatively impacts the JIT's ability to optimize function paths in named easing cases while it helps for custom timings. The suggested change improves performance for both named as well as custom timing cases.
There are 2 distinct cases for `getTimingFunction`: using named easing timings and using custom `cubic-bezier` timings. In the case of named timings the original function proved to be faster then the updated memized function, as the JIT was able to optimize the old switch case fairly well. 
The original performance hit came from dealing with `cubic-bezier`'s due to their required manual string operations and `parseFloat` to convert the string to …
> Fix: Optimize Get Timing Function for animations

- src/core/lib/Matrix3d.ts
- src/core/text-rendering/renderers/SdfTextRenderer/SdfTextRenderer.ts
Matrix3d now stores its values properties instead of a Float32Array. This should potentially cut down on any performance penalty between transforming native JavaScript numbers to Float32 values and vice-versa.
The bottom row of the matrix is now considered a constant [0, 0, 1] which will be true for all 2D operations. The bottom row values hence no longer are stored in the Matrix3d instance.
Also because of the bottom-row assumption the `multiply` operation no longer needs to calculate the bottom row.
The Float32Array, needed by SDF Text Nodes is now only generated (and updated) when needed. This should significantly reduce the number of arrays allocated in an application.
> Optimize Matrix3d storage and operations

- examples/common/ExampleSettings.ts
- visual-regression/README.md
- visual-regression/src/index.ts
Calls to snapshot() now accept a `name` key in the options object. This name, if provided, is appended to the end of the test name and used in the snapshot file name.
> Add ability to name VRT snapshots

- src/core/renderers/webgl/WebGlCoreCtxTexture.ts
The issue occurs when a texture is loading, free() is called on it by the GC, and then there is an error thrown by getTextureData() from the Texture source.
Fixes #275
> Fix assertion error thrown in WebGlCoreCtxTexture getter

- exports/index.ts
Fixes #258 - this creates the missing cjs export point as declared already in `package.json`:
```
"main": "./dist/exports/index.js",
```
> Fix: missing CommonJS export

- src/main-api/INode.ts
A tiny fix allowing `undefined` as `data` value - this clears the dataset prop in the DOM inspector.
> Fix: minor INode data type fix

- src/core/CoreNode.ts
- src/core/textures/NoiseTexture.ts
Also
- NoiseTexture: If cacheId not provided, don't cache the texture
Fixes issue with the `threshold-texture-memory` test
> Fix initial texture loading from CoreNode

- src/core/lib/ImageWorker.ts
- src/core/lib/utils.ts
- src/core/textures/ImageTexture.ts
Support for `file://` loads with relative to absolute path conversion. 
Fixes #287
> Fix image src conversion with local file paths (#287)

- src/core/CoreNode.ts
- src/core/CoreTextureManager.ts
- src/core/renderers/canvas/CanvasCoreRenderer.ts
- src/core/renderers/webgl/WebGlCoreRenderer.ts
- src/core/text-rendering/font-face-types/SdfTrFontFace/SdfTrFontFace.ts
- src/core/text-rendering/renderers/CanvasTextRenderer.ts
- src/core/text-rendering/renderers/SdfTextRenderer/SdfTextRenderer.ts
- src/core/textures/Texture.ts
This refactor eliminates the ctxTextureCache WeakMap and replaces it with access to CoreContextTextures directly from Texture objects themselves.
Since access is more direct and does not require a map look up each time this change should be performance positive. It also simplifies the code a good bit.
This is being done as a foundational step for further Texture memory work.
> refactor(CoreTextureManager): Eliminate ctxTextureCache

- src/core/CoreNode.ts
- src/core/renderers/CoreRenderer.ts
- src/core/renderers/webgl/WebGlCoreRenderer.ts
We are using the same calculations for the renderCoords we use in the .addQuad function in the WebGLCoreRenderer, with this fix we can use the already calculated renderCoords without having to do the calculations again every time a draw call is made.
> passing renderCoords from CoreNode to addQuad

- src/core/lib/utils.ts
When an external image resource is loaded from https, the function convertUrlToAbsolute inside the utils.ts doesn't check if it is a network or internal resource.
> Fix: wrong load external resources when the local protocol is file://

- docs/ManualRegressionTests.md
- examples/README.md
- examples/common/ExampleSettings.ts
- examples/common/MemMonitor.ts
- examples/index.ts
- examples/tests/texture-cleanup-critical.ts
- examples/tests/texture-cleanup-idle.ts
- exports/index.ts
- src/core/CoreTextureManager.ts
- src/core/Stage.ts
- src/core/TextureMemoryManager.ts
- src/core/platform.ts
- src/core/renderers/CoreContextTexture.ts
- src/core/renderers/canvas/CanvasCoreTexture.ts
- src/core/renderers/webgl/WebGlCoreCtxRenderTexture.ts
- src/core/renderers/webgl/WebGlCoreCtxTexture.ts
- src/core/renderers/webgl/WebGlCoreRenderer.ts
- src/core/textures/Texture.ts
- src/core/utils.ts
- src/main-api/Renderer.ts
https://github.com/lightning-js/renderer/assets/6070611/0ecf1514-0b21-46d6-98cb-c1ee02576a8b
- See TSDoc comments for `TextureMemoryManagerSettings` for info on the new configuration settings.
- Adds `monitor` boolean URL param to examples that shows a memory monitor.
- Replaced the term "Texture Garbage Collection" with "Texture Cleanup" to reduce confusion with the Browser/JavaScript's garbage collection process.
Resolves #233
BREAKING CHANGE
> LRU-style Texture Memory Management

- src/core/CoreNode.ts
Implements #316
`scaleRotateTransform` matrix is a waste of memory and computations when `rotation=0` and `scale=1`, which will be the case 99.9% of the time in an average app.
> Only create scaleRotateTransform matrix when needed

- .github/workflows/tests.yml
pnpm/action-setup version 2 is [no longer working](https://github.com/pnpm/action-setup/issues/135). Upgrading to version 4.
> Fix github action

- src/core/CoreNode.ts
This never got moved over from the stripping out of ThreadX
> Fix: Destroy attached children when destroying a Node

- exports/index.ts
- src/main-api/INode.ts
- Also make INodeAnimateProps use BaseShaderController as a default generic type.
Had multiple requests for this.
> Export ShaderController types to API

- src/core/CoreNode.ts
- src/core/Stage.ts
Addressing some of @elsassph comments in #314
> Fix CoreNode.checkRenderProps, cleanup constructor

- Dockerfile
Prior to this change, the VRT Dockerfile installed the latest version of PNPM instead of that is specified in the project's package.json (8.9.2 as of this writing). This led to an issue where everytime you ran the VRT tests in --ci mode it would run pnpm 9 which would incorrectly update the pnpm-lock.yaml file.
This change uses `corepack` to install the project's version of PNPM.
> VRT Dockerfile: Install the correct version of PNPM

- src/core/lib/ImageWorker.ts
Fixes missing function name in image worker blob when building with vite
> fix: Image worker broken with vite build

- src/core/animations/CoreAnimationController.ts
#318 - After stopMethod 'reverse' is done it is removed from animations. Also the animation loops in its entirety not only the reverse part when loop is true.
> Fix: Remove from active animations when reverse stopMethod is complete

- docs/example-projects/custom-shader-effect-texture/src/MyCustomShader.ts
- src/core/renderers/webgl/WebGlCoreShader.ts
- src/core/renderers/webgl/shaders/DefaultShader.ts
- src/core/renderers/webgl/shaders/DefaultShaderBatched.ts
- src/core/renderers/webgl/shaders/DynamicShader.ts
- src/core/renderers/webgl/shaders/RoundedRectangle.ts
- src/core/renderers/webgl/shaders/SdfShader.ts
The PR contains these changes:
- rename GL_FRAGMENT_PRESICISON_HIGH to GL_FRAGMENT_PRECISION_HIGH based on (https://registry.khronos.org/OpenGL/specs/es/3.1/GLSL_ES_Specification_3.10.withchanges.pdf)
- apply GL_FRAGMENT_PRECISION_HIGH inside the fragment and vertex for SdfShader
Tested on:
** FireTv OS 5.2.9.5**
Mozilla/5.0 (Linux; Android 5.1.1; AFTT Build/LVY48F; wv) AppleWebKit/537.36 (KHTML, like Gecko) Version/4.0 Chrome/108.0.5359.220 Mobile Safari/537.36
** FireTv OS 8.1.1.1**
Mozilla/5.0 (Linux; Android 11; AFTKM Build/RS8111.2273N; wv) AppleWebKit/537.36 (KHTML, like Gecko) Version/4.0 Chrome/122.0.6261.140 Mobile Safari/537.36
** Samsung 4K 2018 UE49NU8000**
Mozilla/5.0 (SMART-TV; LINUX; Tizen 4.0) AppleWebKit/537.36 (KHTML, like Gecko) Version/4.0 TV Safari/537.36
** LG WebOS …
> Fix hdpi precision Shader issue for old Chromium device

- README.md
- examples/index.ts
- examples/tests/text-canvas.ts
- exports/canvas.ts
- exports/index.ts
- exports/webgl.ts
- package.json
- pnpm-lock.yaml
- src/core/CoreTextNode.ts
- src/core/Stage.ts
- src/core/text-rendering/TrFontManager.ts
- src/core/text-rendering/renderers/CanvasTextRenderer.ts
- src/core/text-rendering/renderers/SdfTextRenderer/SdfTextRenderer.ts
- src/core/text-rendering/renderers/TextRenderer.ts
- src/core/utils.ts
- src/main-api/Renderer.ts
* Expose Canvas and WebGL Core Renderers under `@lightningjs/renderer/webgl` and `@lightningjs/renderer/canvas` respectively
* Allow RendererMain config to accept a `renderEngine` parameter where the core renderers can be provided
* Expose SDF Text Renderer and CanvasTextRenderer under canvas/webgl exports.
* Allow RendererMain config to accept an array of `fontEngines` where you can provide 1 or 2 Font Engines.
* Fallback with Canvas still works IF Canvas Text Renderer is provided
* Drop memize dependency to reduce overall bundle size, apply simple caching instead
Todo:
In my tests the simple benchmark app went down by `20 kb` by just using 1 font engine to `40 kb` when only using canvas and canvas rendering.
Note: This is a breaking init change, handle with care.
> Support for Tree Shakable Canvas/WebGL renderer and Font Engines

- src/core/CoreNode.ts
The inspector allows setting a custom data object. However some also use it for `data` from API. Adding the get / set to allow devs to access the data that they set.
> fix: add get / set for data object

- examples/tests/absolute-position.ts
- src/core/CoreNode.ts
Fixes #354:
- include `mount` property when calculating `absX` and `absY`
- create new example page `absolute-position` to test `absX` and `absY` with different values of `mount`, `scale`, `rotation` and `pivot`
> Fix: Add support for mount property in absX and absY

- exports/canvas.ts
- exports/index.ts
- exports/inspector.ts
- exports/utils.ts
- typedoc.config.cjs
I noticed the current typedoc config was not up to date since the split from threadx, and the canvas/webgl changes. This fix exposes all the good stuff again.
> updated typedoc config

- examples/tests/viewport-events.ts
- src/core/CoreNode.ts
- src/core/Stage.ts
This PR changes the CoreNode update behavior, including how bounds detection works. Instead of creating local strictBoundaries and preLoad boundaries, the boundaries are inherited from the parent unless clipping is enabled.
Bounds detection added a significant CPU impact to the the rendering loop of the L3 Renderer, causing low end devices to struggle to keep up as the CPU would be overloaded and not in time enough to provide new render instructions to the GPU. 
Bounds detection is needed to ensure we only draw what is required on screen / view port and do not render nodes that are outside of the view ports bounds. 
Previously every node would on every `update()` calculate what its `strictBound` and `preloadBounds` where based off of its world position. This is quite expensive to do and …
> Performance: Modify bounds detection to inheritance when clipping is disabled

- src/core/CoreNode.ts
- src/core/lib/utils.ts
Fixes #371 and various other parent/child updates with Bounds detection.
Changes:
* children update state, whenever the branch becomes active again they will be propagated accordingly
* Alpha and clipping now properly trigger children updates when active again
* Larger then bound detection, for full width child nodes (one of the clipping VRT tests)
* Ability to handle dimension-less "holder" nodes with boundary checks
* Small child iteration loop optimizations
Small sacrifices on performance as more parts of the tree will remain active (though still 125 -> 650k ops/s) , the original 2.1.0 release was a bit too aggressive marking part of the render tree "dead" due to not being able to handle "holder" nodes who do not have dimensions and once marked inactive would discard children updates.
> Boundary detection fixes

- .eslintrc.cjs
- src/core/CoreNode.ts
- src/core/renderers/webgl/WebGlCoreRenderer.ts
Hopefully reduces a bit of garbage collection. Only removing forEach on most used areas of the code. Also updated eslint to disable the no null assertion so typescript doesn't complain about undefined children.
> perf: Replace forEach with for loops

- src/core/CoreNode.ts
On low powered devices / heavy operation UI's there might be a race condition where the animation/transition is ends prior to the update loop finishing its first run. This causes the isRenderable to not be evaluated in time for the alpha changes to take affect.
This PR ensures isRenderable is always re-evaluated on an alpha change and moves the worldAlpha calculation slightly up to ensure it gets handled in the correct order if its a 1 shot update. 
Also save a little processing by ensuring on alpha change the children only re-evaluate the worldAlpha and not a global, reducing child update processing.
Fixes #388 
Might fix #372  - though cant reproduce to validate on my setup (even with 20x slowdown).
> fix: re-evaluate isRenderable on alpha change

- src/core/CoreNode.ts
Fixes an issue where out-of-bounds or non-renderable child nodes of a render texture remain invisible
> Flag parent if render texture child has changes

- src/core/text-rendering/renderers/TextRenderer.ts
Functionally the same thing - fromEntries requires Chrome 73. This will allow renderer to work on older devices a bit easier without vite needing to transpile it away.
> compat: Remove fromEntries for older browser support

- src/main-api/Inspector.ts
Adds the bound state in an attribute:
This makes it easier to debug if nodes marked out of bounds when they're not suppose to due to positioning issues.
> feat: Add bound status to a div state attribute in the Inspector

- src/common/IAnimationController.ts
- src/core/animations/CoreAnimationController.ts
Added `scheduled` state for animations with delay. `scheduled` will change to `running` as soon as the  animation _really_ starts (triggered by the `onAnimating` hook).
This allows to make a distinction between an animation that is actually in the process of animating (i.e. `running`) and animations that are awaiting the delay to start animating (i.e. `scheduled`).
> Scheduled state for animations with delay

- src/core/renderers/webgl/WebGlCoreCtxTexture.ts
- Add try/catch block in WebGlCoreCtxTexture `load` method to manage the error thrown by `createNativeCtxTexture`
- Set the texture state to failed on error thrown
> Fail gracefully createNativeCtxTexture in WebGlCoreCtxTexture load

- src/core/textures/ImageTexture.ts
This PR addresses an issue specific to 2017 Samsung TVs, which do not support the createImageBitmap method.
**Testing**
Tested on 2017 Samsung TVs with renderer+solid.
> fix: image size on browsers without createImageBitmap

- src/core/text-rendering/TrFontManager.ts
- src/core/text-rendering/font-face-types/TrFontFace.ts
- src/core/text-rendering/renderers/CanvasTextRenderer.ts
The FireFox browser was throwing an error when using the default font for canvas. 
When the canvas text renderer tries to add the default font (fallback font).  However during the creation of the WebFont (line: 120 CanvasTextRenderer) it creates a FontFace which creates a family property which is an empty string in FireFox. This is where we run into problems because that empty string is used as a key later on. 
I have resolved the issue by building in a fallback that in case the family returns an empty string it falls back to the fontFamily property of its super class.
> Resolved sans-serif font issue for firefox browser

- src/core/renderers/webgl/shaders/effects/LinearGradientEffect.ts
- src/core/renderers/webgl/shaders/effects/RadialGradientEffect.ts
Resolved an issue where the linearGradient didn't return the proper effect key that it need to differentiate between two different linearGradient effects. Since the radialGradient had the same issue I fixed it for that effect too.
Resolves issue #411
> Fixed LinearGradient/RadialGradient effect for DynamicShader 

- src/core/renderers/webgl/WebGlCoreRenderer.ts
**Issue**: When rendering parts on the render tree to a texture ( RTT ) and the `clearColor` is set to a solid color rather than being transparent, this color is used to clear the colorbuffer of the texture's framebuffer. This results in render textures displaying a solid background color instead of being transparent.
This PR addresses this issues by setting the `gl.clearColor` to transparent before the render to texture pass begins and restoring it when the pass is complete.
Before: 
After:
> Set gl.clearColor to transparent for render-to-texture nodes

- src/main-api/Inspector.ts
Proxies introduce a delay and differences in update graph behaviour which break the RTT parent/child updates on nodes itself, to avoid the issue only enable traps for inspector elements that we're actually interested in.
Fixes #429
> fix: [Inspector] drop Proxies, set selective Object.defineProperties traps

- src/main-api/Inspector.ts
this fixes https://github.com/lightning-js/renderer/issues/436
> fix: Inspector breaks animationController

- src/core/CoreNode.ts
Removing a redundant check that was introduced with the recursive update loop fix. This prevented the first frame of an RTT scene to render all RTT textures correctly.
> Fix first frame with RTT

- src/main-api/Inspector.ts
fixes https://github.com/lightning-js/renderer/issues/444
> fix(inspector): top left calculated with mount

- src/core/lib/WebGlContextWrapper.ts
- src/core/renderers/webgl/WebGlCoreCtxSubTexture.ts
- src/core/renderers/webgl/WebGlCoreCtxTexture.ts
- src/core/textures/ColorTexture.ts
- src/core/textures/Texture.ts
Fixes running on Chrome 38
Fixes #389
Before:
After:
> fix: change ColorTexture to use Uint8Array instead of ImageData

- src/core/CoreShaderManager.ts
- src/core/renderers/webgl/shaders/SdfShader.ts
- src/core/text-rendering/renderers/SdfTextRenderer/SdfTextRenderer.ts
- src/main-api/ShaderController.ts
Fixed an issue where running the examples test with renderMode as canvas. Upon loading the SdfShader no properties are passed as parameter causing issues with when creating the UnsupportedShader for canvas.
This is mostly a temporary solution as the shaders are resolved differently in the shader rework i'm working on.
> fix issue when running canvas renderMode

- examples/tests/rtt-dimension.ts
- src/core/CoreNode.ts
> fix: Fix RTT Clipping and improve RTT parent lookup

- examples/tests/rtt-nested-clipping.ts
- src/core/renderers/webgl/WebGlCoreRenderOp.ts
This PR resolves an issue where children nodes rendered as part of a render-to-texture were not properly clipped according to the parent node's bounds. The fix ensures that clipping is correctly applied within the render-to-texture pipeline, maintaining visual consistency and expected behavior for nested scenes
> Correct clipping of children in render-to-texture nodes

- src/core/CoreTextureManager.ts
- src/core/lib/ImageWorker.ts
Instead of using an additional postMessage init flow, directly set the variables in the JS Blob before instantiating the worker.
Note:
CI will fail because of a race condition with 2 tests where the createImageBitmap detection is still happening and an image request is already being made, this will need to be addressed with texture throttling instead of trying to jump through hoops with the current texture source download + ctxCoreContext construction.
> Simplify ImageWorkerManager initialization

- src/main-api/Renderer.ts
This is used to already create a canvas object and render a logo, pass this on to Lightning and it will be overwritten once the app comes up
> feat: add optional external canvas for rendering

- src/core/CoreNode.ts
- src/core/Stage.ts
- src/core/textures/Texture.ts
This PR refactors Texture Throttling in the following ways:
- 🕒 Async RTT Texture Loading: When an RTT node is set, wait for the texture to load asynchronously.
- 🗑️ Improved Texture Cleanup: When a texture is freed, its source texture is now also marked as freed. Fixes a bug where textures weren't returning after memory cleanup.
- 🔄 Auto-Trigger Texture Loading: Refactored isRenderable owner changes to automatically call texture loading if the texture state is freed or initial.
RTT Changes: Use `test=rtt-dimension`. 🖼️ You should see race conditions occurring prior to this PR.
Texture Freed Fix: Add a rocko.png to the `test=texture-cleanup-critical` test and move it in and out of the screen to validate. 🎯 (Not the prettiest, but it works!). Might create an automated test for this in the …
> 🎨 Refactor CoreNode Renderability Logic 🚀

- src/core/renderers/webgl/shaders/effects/RadialGradientEffect.ts
Causing issues where cached linearGradients is shared with radialGradient
> fix: radialGradient cache key was using linearGradient

- src/core/CoreNode.test.ts
- src/core/CoreNode.ts
- src/core/CoreTextNode.ts
- src/core/Stage.ts
- src/core/text-rendering/font-face-types/SdfTrFontFace/SdfTrFontFace.ts
- src/core/textures/Texture.ts
✨ What changed? ✨ 
* Decouple **isRenderable** from **hasRenderableOwner** as textures can be loaded asynchronously.
* Refactored the `isRenderable` detection:
- If a node has `alpha = 0` or is off screen its not renderable
- If a node has dimensions and color properties, its marked renderable and we assume its a `ColorTexture`.
- If a node has a texture, it will be marked as a renderable owner. Which will trigger loading of the texture (if its the first owner)
- If the texture is loaded, it is marked renderable
* On `renderQuads` we assume everything has a texture if not we set the defaultTexture for 1x1 sampling. This is implicit but matches the old behaviour.
* `CoreTextNode` overwrites behaviour and checks for text !== ''. 
* Also fixed a bug where the default texture was still …
> Refactor isRenderable detection

- src/core/CoreNode.ts
this fix the issue that elements with shaders but without color are not marked as renderable
> fix: added missing check for shader existence

- src/core/text-rendering/font-face-types/SdfTrFontFace/SdfTrFontFace.ts
Stop gap solution, ideally we do want SDF Font Face textures cleaned up if we can detect they have no renderable owners anymore to save as much memory as we can in case we hit critical levels.
However for now prevent Font Face textures from being cleaned up until we have proper guards/reloads in the SDF Font Renderer at the expense of keeping the Font atlas always in memory regardless if its being used.
> fix: prevent cleanup of SDF Font Face textures for now

- src/core/CoreNode.ts
- src/core/CoreTextureManager.ts
The `textureOptions.preload` was removed during the Texture Throttling refactor, reintroduced it even though its loading will be throttled.
While looking at the properties, decided to move `preventCleanup` to `textureOptions` instead of as a property on the `CoreNode`. Technically this controls the behaviour of the texture, not the core node. Hence it better belongs on `textureOptions`.
Will throw a deprecation warning in dev mode for a couple of releases and then we'll drop it.
> fix: deprecate CoreNode.preventCleanup and re-introduce preload option

- .github/workflows/tests.yml
Its not quite Jan 30th yet but seems GHA is a bit early with disabling v3
> fix: update upload-artifact action to version 4 in Github Actions

- src/core/lib/ImageWorker.ts
- src/core/lib/utils.ts
- src/core/textures/ImageTexture.ts
In Chrome versions before 67, data: URLs were treated as uncertain-origin resources for security reasons. In this context:
XMLHttpRequest did not allow access to base64 (data:) URLs because it violated CORS (Cross-Origin Resource Sharing) policies. Even though a data: URL is "local," it was still considered a different origin from the domain where the request was made.
> fix: Exclude Base64 images from image worker handling

- src/core/CoreTextureManager.ts
- src/core/Stage.ts
- src/main-api/Renderer.ts
Align to L2 time based approach.
Will use `textureProcessingTimeLimit` by default set to `10ms` (just like L2) to process textures. 
Eg. under constraints generating mixed 1k nodes:
> refactor: update texture processing to use time limit instead of item limit

- examples/common/MemMonitor.ts
- src/core/TextureMemoryManager.ts
- src/core/lib/textureSvg.ts
- src/core/renderers/canvas/CanvasCoreRenderer.ts
- src/core/renderers/webgl/WebGlCoreCtxTexture.ts
- src/core/textures/ImageTexture.ts
- src/main-api/Renderer.ts
The Renderer was _off_ in its GFX Memory allocation, most cases it would report 50 Mb GFX usage while the real usage was >150 Mb.
This was due to:
- mipmaps being incorrectly enabled
- no baseline, calculations started at 0
- no texture padding
Introduced `baselineMemoryAllocation` memory setting to set a baseline usage of your device. For example on my test device (RPI3b+ with WPEWebKit 2.46) an empty Canvas with a WebGL1 context uses 25 Mb. Every device you have will have a base allocation for just the WebGL context alone, adjust this setting to set that immutable baseline.
All textures subsequently loaded will go on top of that baseline.
Removed mipmap's on Textures - we're using fixed scale textures and are not making use of Level-Of-Detail. Enabling mipmap's on textures generates a …
> Fix memory allocations

- examples/tests/texture-cleanup-critical.ts
- src/core/CoreTextureManager.ts
- src/core/Stage.ts
- src/core/TextureMemoryManager.ts
- src/core/textures/Texture.ts
The memory cleanup routine would resort on every run, this is quite expensive to do during frame generation time. Instead keep a list of orphaned textures, once we need to clean up pick the first one added to that list until we reach our threshold using a simple while loop.
> Improve memory cleanup performance

- examples/tests/texture-memory-allocation.ts
- src/core/TextureMemoryManager.ts
Regression introduced by #507 
- Check if orphaned entry is already in the list, if so re-add it at the end (to avoid duplicate entries)
- If a texture became renderable again during the cleanup routing, skip it
- On non-critical cleanup spend max 10ms 
Fixes #511
> fix: duplicate orphaned texture entries, check for renderable and timing

- pnpm-lock.yaml
- src/core/lib/ImageWorker.ts
- src/core/text-rendering/font-face-types/SdfTrFontFace/SdfTrFontFace.ts
- src/core/text-rendering/font-face-types/utils.ts
- src/core/textures/ImageTexture.ts
This PR fixes the issue where the assets in locally packaged apps are unresolved and fail to load. Now the local assets are loaded successfully and served to the app.
This has been tested locally on various WebOS devices
> fix: resolve issues with fetching local assets when serving files from the file protocol

- src/core/CoreNode.ts
Fixed an issue where switching from one shader to a different shader does not trigger the calculation of shader specific values when needed.
> fixed issue with shader switching

- src/core/CoreNode.test.ts
- src/core/CoreNode.ts
- src/core/Stage.ts
Flag was deprecated in #486 and released in 2.9.0 with a warning/messaging.
This is moved to texture Options for better clarity.
This PR will drop it entirely from 3.0.
> Remove deprecated preventCleanup flag

- src/main-api/Renderer.ts
settings.inspector is a boolean, so it's never null
> Fix inspector is enabled even though it isn't

- src/core/renderers/webgl/WebGlRenderer.ts
Updating the `glClearColor` also triggers a `glClear`, this can lead to unwanted behaviour in the case where the render is idle.
> Prevent glClearColor when clear color is changed

- src/core/CoreNode.ts
The width and height where not updating on textures due to extra checks.
This happened on animation but also when changing width and height
> #547 Fixed. Width and Height not updating on textures

- examples/tests/texture-memory-allocation.ts
- src/core/CoreTextureManager.ts
- src/core/lib/ImageWorker.ts
- src/core/textures/ImageTexture.ts
If during texture load the source was unavailable (e.g. 404 or temp network issue) the texture would never get reloaded.
This change enables reloading the texture if it goes in bound again, forcing a redownload. If the network error was temporarily it should resolve on the second attempt.  If the error is permanent the UI should do a fallback image instead based on the `failed` event.
Additionally fixed a race condition that if an texture was yanked out of the throttle queue while it was uploading, it would immediately get uploaded again on subsequent texture load.
Also enabled logging of failed images when in dev mode.
> Fix failed textures getting stuck

- examples/tests/shader-rounded.ts
- src/core/renderers/CoreShaderNode.ts
- src/core/renderers/canvas/CanvasShaderNode.ts
- src/core/renderers/webgl/WebGlShaderNode.ts
- src/core/shaders/templates/BorderTemplate.ts
- src/core/shaders/templates/HolePunchTemplate.ts
- src/core/shaders/templates/RoundedTemplate.ts
- src/core/shaders/templates/RoundedWithBorderAndShadowTemplate.ts
- src/core/shaders/templates/RoundedWithBorderTemplate.ts
- src/core/shaders/templates/RoundedWithShadowTemplate.ts
- src/core/shaders/templates/ShadowTemplate.ts
- src/core/shaders/utils.ts
- fixed an issue(#568) where node width / height changes were not checked during shader update.
- moved shaderUtils.ts to shaders folder and renamed to utils.
> Include node dimensions to shader value key + minor refactor

- src/core/shaders/webgl/RoundedWithBorder.ts
- src/core/shaders/webgl/RoundedWithBorderAndShadow.ts
Fixed the webgl shaders that draw borders,  now it doing a check that when all border values are zero its skips the border calculations and draw functions.
> fixed shader render issue when border is 0

- src/core/CoreTextureManager.ts
* Remove download source queue, this should be handled by the network process itself
* Only throttle image textures, all the others get uploaded directly
Visibly faster image loading, reduce strain on loading
Prioritize loading of non-image textures for faster rendering to provide earlier TTMU
> Simplify Texture Throttling

- examples/tests/texture-alpha-switching.ts
- src/core/CoreTextureManager.ts
- src/core/TextureMemoryManager.ts
- src/core/textures/Texture.ts
If we made really quick changes to an image node (e.g. alpha 0 to 1 back 0) you could end up with race conditions that caused a duplicate cleanup of the texture. Resulting in the issues seen (and guarded) with #597 
This change addresses the root cause by avoiding duplicate `load` of textures and cleaning up textures that are in an transitional state (`fetching` / `fetched` / `loading` etc).
This avoids a race condition where the memory manager tries to cleanup a texture that is still `loading` or similar, which is especially prevalent on CPU starved devices with heavy transitions.
> Fix transitional texture changes

- Dockerfile
Port from v3 - else the corepack prepare will fail with some certificate/key error for pnpm.
> fix: update PNPM installation command in Dockerfile

- examples/index.ts
- examples/tests/default-fps-animation.ts
- src/core/Stage.ts
- src/core/platform.ts
- src/main-api/Renderer.ts
Throttle RAF by targetFPS for smoother animations.
This effectively caps all rendering, instead of the old PR https://github.com/lightning-js/renderer/pull/605 that capped only animations. The animations route led to glitchy animations as the progress and left over frametime went out of sync.
By capping the entire upload loop everything neatly aligns and the system will not cross the desired targetFPS. 
Demo:
https://github.com/user-attachments/assets/bfb7660e-ce67-4848-8682-e0046c924ab3
> Implement Target FPS throttling

- src/core/text-rendering/CanvasTextRenderer.ts
6x slowdown:
with this PR: create: 268.96ms ±18.12
without: create: 743.60ms ±38.26
for reference:
beta 9: create: 426.59ms ±40.61
This does include `{ willReadFrequently: true }` as it did have a serious impact on perf in Chrome - we will need to test on a WPE device to get the impact on a real device. I'd imagine GPU vs CPU rendering to be of a bigger impact there.
> perf: performance changes to the canvas text renderer

- src/core/Stage.ts
Fixed color resolving, for the gradient it was always picking the top or bottom color and ignored the left, right because top / bottom already had a color normalized to fallback
> fixed resolved defaults regarding color

- src/main-api/Renderer.ts
Events like `idle` `fpsUpdate` and `frameTick` where not part of the typedocs of the renderer, this PR adds TS structures to get the events added to the typedoc for more clarity
> Add events to the docs

- examples/tests/animation.ts
- exports/index.ts
- src/core/animations/CoreAnimation.ts
- src/core/utils.ts
Allows specifying a timing function instead of selecting from predefined easings or a cubic-bezier ease.
I've reused the `easing` property to set the timing function, so you can specify a function or a string as before.
> feat: Allow custom timing functions for easing

- src/core/CoreNode.ts
- src/core/textures/ImageTexture.ts
- src/core/textures/Texture.ts
mistakes where made
```
this.maxRetryCount = props.maxRetryCount as number;
```
Setting the maxRetryCount from an unresolved `props` instead of `resolvedProps` isn't a great idea. This could lead to `maxRetryCount` is `undefined` and it goes in an infinite loop.
Also put the stop to check for retries up in the `CoreNode` to toggle entire node visibility and take it out of the render tree entirely (== cleaner)
> fix: infinite retry loops on unresolved image props

- src/core/CoreNode.ts
- src/core/textures/SubTexture.ts
On send the failed event from the `CoreNode` when the `retry` count has exhausted and we've stopped retrying.
> Fix failed event on retry exhausted

- src/core/TextureMemoryManager.ts
- src/core/platform.ts
The defrag system was introduced to avoid endlessly growing the `this.loadedTextures` however this introduced:
* Additional function calls
* Idle processing
* Potential race conditions when the defrag ran inbetween operations (like 1 frame idle)
Having a memory allocation with potentially lots of `null` items isn't going to affect memory usage much. Since we want low-latency, zero-copy, texture memory placement this PR replaces the defrag system with a Slot Reuse system.
It simply does:
* On texture delete, `null` the place in the texture array
* On texture creation, pick a previously `null` spot or `append` if there are none
This avoids potential race conditions and the extra overhead of a defragmentation system while keeping the textures neatly packed at the beginning.
The only downside …
> refactor(textures): replace defrag system with a slot reuse system
