- examples/tests/dynamic-shader.ts
- src/core/renderers/webgl/shaders/DynamicShader.ts
- src/core/renderers/webgl/shaders/effects/LinearGradientEffect.ts
- src/core/renderers/webgl/shaders/effects/RadialGradientEffect.ts
Chris found an issue with gradients that contained alpha lower than 1. This PR resolves that issue.
> fixed mixing gradient colors with maskcolor

- examples/tests/animation.ts
- src/core/animations/CoreAnimation.ts
This fixes looping an animation that has `stopMethod: 'reverse'`
> Fix looping animations with `stopMethod: 'reverse'`

- package-lock.json
- package.json
Updated threadx dependency which contains the globalthis fix.
> Updated threadx dependency to latest version

- package.json
This allows vite to remove Threadx from bundling
> set sideEffects to false to enable treeshaking

- examples/tests/text-offscreen-move.ts
- src/core/CoreTextNode.ts
- src/core/lib/utils.ts
- src/core/text-rendering/renderers/CanvasTextRenderer.ts
- src/core/text-rendering/renderers/SdfTextRenderer/SdfTextRenderer.ts
- src/core/text-rendering/renderers/TextRenderer.ts
Also included are some performance optimizations on how text renderer state gets updated.
Resolves #50
> Fix issue that caused text moved from offscreen to not render properly

- examples/tests/animation.ts
- src/core/animations/CoreAnimation.ts
This fixes the reported issue where animations do not always progress all the way to their destination before stopping.
> Fix issue that caused animations not to finish all the way

- src/core/renderers/webgl/shaders/effects/BorderEffect.ts
Border alpha was not properly calculated so I fixed the formula
> BorderEffect alpha fix

- src/env.d.ts
- src/utils.ts
For prod builds with vite this will code shake all the assertTruthy statements. Tested with Solid and nothing breaks with it removed in prod. Open for consideration :-)
> remove assertions in prod builds

- visual-regression/src/index.ts
Previously the VRT test runner would hang if a snapshot was missing
> Visual Regression: Trigger error if snapshot is missing

- exports/main-api.ts
- src/core/CoreShaderManager.ts
fixes: [93](https://github.com/lightning-js/renderer/issues/93)
> chore: exported EffectsProps interfaces

- src/common/CommonTypes.ts
- src/core/Stage.ts
- src/main-api/ICoreDriver.ts
- src/main-api/RendererMain.ts
- src/render-drivers/main/MainCoreDriver.ts
- src/render-drivers/threadx/ThreadXCoreDriver.ts
- src/render-drivers/threadx/ThreadXRendererMessage.ts
Allows developers to tap into frame loop
> Added frametick event, fired upon every frame start.

- src/main-api/Inspector.ts
Feedback from https://github.com/lightning-js/renderer/issues/180
> Inspector: Put divs on top, attach div to node and handle images differently

- src/core/text-rendering/TrFontManager.ts
should've left it with the reduce 😭
> fix: warning for font weight

- src/core/lib/ImageWorker.ts
Updating image worker to ES5 features
Resolves: #190
> refactor: image worker to ES5

- src/core/CoreNode.ts
- src/core/renderers/webgl/WebGlCoreCtxRenderTexture.ts
- src/core/renderers/webgl/WebGlCoreCtxTexture.ts
- src/core/renderers/webgl/WebGlCoreRenderer.ts
- src/core/textures/RenderTexture.ts
Small refactor of RTT code that resolve my PR comments:
- https://github.com/lightning-js/renderer/pull/186#discussion_r1513321615
- https://github.com/lightning-js/renderer/pull/186#discussion_r1513331368
> refactor(RTT): move WebGL logic into new WebGlCoreCtxRenderTexture

- RELEASE.md
It's a good idea to do this after checking out main and stashing your working tree to make sure you have the latest changes.
> RELEASE.md: Add instruction to pull new changes

- src/core/lib/ImageWorker.ts
Invalid token till Chrome 55...
> fix: remove async keyword, not needed

- src/core/lib/ImageWorker.ts
> ImageWorker: Fix issue with simultaneous requests for the same URL

- src/core/renderers/webgl/WebGlCoreRenderer.ts
> Mark default texture as always renderable

- src/core/Stage.ts
- src/core/TextureMemoryManager.ts
> Guarantee Texture GC happens after Node updates

- src/core/CoreTextureManager.ts
- src/core/lib/ImageWorker.ts
When numImageWorkers is 0 the imageWorkerManager was still initizlizated
> fix: numImageWorkers=0

- src/core/CoreNode.ts
Slightly changed the checkRenderBounds function, and simplified the emitting process according to the changes Frank made for PR #231
> RenderState/Viewport Event changes to DEV

- src/core/lib/ImageWorker.ts
Replaces https://github.com/lightning-js/renderer/pull/245
> refactor: Make ImageWorker work on older Tizen TVs

- package.json
- pnpm-lock.yaml
- src/core/CoreNode.test.ts
- src/core/CoreNode.ts
> #304 Color setter cascade to subcomponents

- examples/tests/destroy.ts
- examples/tests/ds-effect-radial-progress.ts
- examples/tests/dynamic-shader-circle-border-radius.ts
- examples/tests/dynamic-shader.ts
- examples/tests/hole-punch-effect.ts
- examples/tests/shader-animation.ts
- src/core/CoreShaderManager.ts
- src/core/renderers/webgl/shaders/DynamicShader.ts
- src/main-api/DynamicShaderController.ts
- src/main-api/Renderer.ts
Effects that do not have names cannot be mutated/animated after creation.
Also add some more documentation around createShader/createDynamicShader/createEffect.
> Make effect names optional

- src/core/animations/CoreAnimation.ts
Applied CoreAnimation suggestions by @elsassph in #314
> Refactored Core Animation after latest changes

- src/core/renderers/webgl/shaders/RoundedRectangle.ts
Following the CSS3 spec
https://drafts.csswg.org/css-backgrounds-3/#corner-overlap
> Clamp the radius on the RoundedRectangle / RadiusEffect shader

- src/core/Stage.ts
- src/core/renderers/webgl/WebGlCoreRenderer.ts
- src/main-api/Renderer.ts
> Add stage option to define quad buffer size (#335)

- src/main-api/Renderer.ts
Allow inspector to be optional
> fix: Typescript settings for inspector

- src/core/renderers/webgl/WebGlCoreRenderer.ts
- src/core/renderers/webgl/shaders/DynamicShader.ts
Resolved alpha issue with shaders #352. Traced it back to automatic alpha value not being updated on time, and it not being properly tested when checking if it can be batch rendered by the dynamic shader.
> fix alpha issue dynamic shader

- docs/example-projects/custom-shader-effect-texture/src/index.ts
Fixed the way the Renderer is being setup because it stopped working with the latest Renderer releases
Related issue: #370
> Fix example project custom-shader-effect-texture

- README.md
> Removed beta terminology from the readme.

- src/core/renderers/webgl/WebGlCoreShader.ts
useProgram was used two times, so I removed one line.
> removed useProgram call WebGlCoreShader

- src/core/renderers/canvas/CanvasCoreRenderer.ts
- src/core/text-rendering/renderers/CanvasTextRenderer.ts
this fixes https://github.com/lightning-js/renderer/issues/433
> fix: re-apply canvas text color with alpha

- src/main-api/Inspector.ts
Data attr missing in list for Proxy so any changes to data was not reflected in inspector output.
> fix: data attr in inspector not reactive..

- src/core/Stage.ts
- src/main-api/Renderer.ts
> feat: expose cleanup feature

- src/core/lib/utils.ts
- src/core/textures/ImageTexture.ts
this fixes https://github.com/lightning-js/renderer/issues/524
> fix: base64 images and xhr on chrome <67

- docs/example-projects/custom-shader-effect-texture/src/MyCustomTexture.ts
- docs/example-projects/custom-shader-effect-texture/src/index.ts
Hi, I just found the example project is broken, hope I'm doing the right thing. Now it can be rendered like the following screenshot.
> docs: fix broken example project

- src/core/shaders/canvas/LinearGradient.ts
- src/core/shaders/canvas/RadialGradient.ts
- src/core/shaders/canvas/RoundedWithBorder.ts
- src/core/shaders/canvas/RoundedWithBorderAndShadow.ts
- src/core/shaders/canvas/RoundedWithShadow.ts
- src/core/shaders/webgl/HolePunch.ts
- src/core/shaders/webgl/LinearGradient.ts
- src/core/shaders/webgl/RadialGradient.ts
- src/core/shaders/webgl/RoundedWithBorderAndShadow.ts
Added some minor performance boost by using a const when using this.props more than 3 times. Same with computed.
> when using this.props / computed more than 3 times use const.

- src/core/CoreNode.ts
- src/core/CoreTextNode.ts
- removed update type ScaleRotate
- reduced the amount of functions fired in update function
> Improved update function

- examples/index.ts
- examples/tests/default-fps-animation.ts
- src/core/Stage.ts
- src/core/platforms/web/WebPlatform.ts
- src/main-api/Renderer.ts
v2 port forward of https://github.com/lightning-js/renderer/pull/608
> Feat: fps throttle
